### ISSUE TITLE
 Solax integration occasionally returning all zeros

### ISSUE THREAD

**Issue by squishykid** [squishykid/solax#67]
Cloned from https://github.com/home-assistant/core/issues/66912

**Comment by VadimKraus** [comment]
See #68 for a possible solution. 
This solution relies a validation error and the home assistant retry mechanism(i.e. exception handling of user of this library).

**Comment by joseal** [comment]
Any ETA, went his fix is going to be released? This is impacting a ton of users... thank you!

**Comment by VadimKraus** [comment]
Updated #68.

**Comment by VadimKraus** [comment]
@squishykid this is resolved I guess

**Comment by jesserockz** [comment]
This is still an issue: https://github.com/home-assistant/core/issues/146493

**Comment by squishykid** [comment]
@jesserockz I think the reason this has not been fixed is that the integration currently does the discovery phase every time the inverter or home assistant has been restarted. So if you have an inverter which turns off overnight, HA will re-do the discovery phase in the morning, and if we have these 0s as a failed response, it will never discover correctly.

So I think we finally need to address the discovery phase issue and move that to the integration setup phase. Once we have that we can implement the zero-response-rejection.

Just thinking out loud though, let me know if there's another approach we could use here.

**Comment by jesserockz** [comment]
My inverter does report some of the values as 0 overnight, but the totals don't go away, except sometimes while it is starting up when the sun comes up in the morning.

**Comment by squishykid** [comment]
@jesserockz do you happen to have a battery connected to your inverter?

**Comment by jesserockz** [comment]
No. I have an x1-boost. AC coupled only.
